module.exports = {
    "up": `CREATE TABLE IF NOT EXISTS orders (
        id INT AUTO_INCREMENT PRIMARY KEY,
        order_id INT NULL,
        user_id INT NULL,
        product_id INT NULL,
        order_date DATETIME NULL,
        order_amount DECIMAL(10,2) DEFAULT 0.0,
        shipping_amount DOUBLE(15,2) DEFAULT 0.0,
        discount_amount DECIMAL(8,2) DEFAULT 0.0,
        total_amount DOUBLE(15,2) DEFAULT 0.0,
        payment_mode VARCHAR(255) NULL,
        payment_status VARCHAR(255) NULL,
        bill_name VARCHAR(225) NULL,
        bill_mobile VARCHAR(225) NULL,
        bill_address VARCHAR(225) NULL,
        bill_pincode VARCHAR(225) NULL,
        bill_city VARCHAR(225) NULL,
        bill_state VARCHAR(225) NULL,
        bill_country VARCHAR(225) NULL,
        bill_email VARCHAR(225) NULL,
        ship_name VARCHAR(225) NULL,
        ship_mobile VARCHAR(225) NULL,
        ship_address VARCHAR(225) NULL,
        ship_pincode VARCHAR(225) NULL,
        ship_city VARCHAR(225) NULL,
        ship_state VARCHAR(225) NULL,
        order_status VARCHAR(225) NULL,
        order_comments TEXT NULL,
        gst_no VARCHAR(225) NULL,
        is_deleted TINYINT DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )`,
    "down": "DROP TABLE IF EXISTS orders"
}